
package org.hjackson.llm;
import java.io.File;
import java.io.IOException;
import java.io.RandomAccessFile;
import java.lang.foreign.Arena;
import java.lang.foreign.MemorySegment;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;
import java.time.Duration;
import java.time.Instant;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
class GPT2Test {
    float epsilon = 1e-2f;
    private int B;
    private int T;
    private GPT2 model;
    private long file_size;
    private Arena memoryArena;
    private MemorySegment mappedFile;
    private ParameterTensors expected_grads;
    private ByteBuffer byteBuffer;
    private int C;
    private int V;
    private int maxT;
    private int L;
    private int[] state_header;
    private byte[] mem;
    private int cpos;
    private int n;
    private int Vp;
